import {
  Activity,
  ArrowRight,
  CalendarDays,
  Camera,
  Check,
  ChevronLeft,
  ChevronsUpDown,
  Clock,
  Copy,
  Download,
  Ellipsis,
  History,
  LayoutDashboard,
  Link2,
  LogIn,
  LogOut,
  Menu,
  Monitor,
  Paperclip,
  Pencil,
  Plus,
  ReceiptText,
  ScrollText,
  Search,
  Settings2,
  Smartphone,
  Tags,
  Trash2,
  TriangleAlert,
  UserRound,
  Users,
  X,
  type LucideIcon,
} from "lucide-react";

/** Ícones do painel (biblioteca Lucide — traço uniforme e profissional). */
const ICONES = {
  painel: LayoutDashboard,
  recibo: ReceiptText,
  etiqueta: Tags,
  pessoas: Users,
  ajustes: Settings2,
  calendario: CalendarDays,
  mais: Plus,
  baixar: Download,
  sair: LogOut,
  entrar: LogIn,
  alerta: TriangleAlert,
  check: Check,
  relogio: Clock,
  lapis: Pencil,
  lixo: Trash2,
  clipe: Paperclip,
  camera: Camera,
  voltar: ChevronLeft,
  seta: ArrowRight,
  seletor: ChevronsUpDown,
  menu: Menu,
  link: Link2,
  copiar: Copy,
  usuario: UserRound,
  busca: Search,
  logs: ScrollText,
  online: Activity,
  historico: History,
  celular: Smartphone,
  computador: Monitor,
  fechar: X,
  mais_opcoes: Ellipsis,
} satisfies Record<string, LucideIcon>;

export type NomeIcone = keyof typeof ICONES;

export function Icone({ nome, tamanho = 18, className }: { nome: NomeIcone; tamanho?: number; className?: string }) {
  const Componente = ICONES[nome];
  return <Componente size={tamanho} strokeWidth={1.9} absoluteStrokeWidth={false} aria-hidden="true" className={className} />;
}
